language: python
python:
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  nosetests --with-coverage --cover-erase --cover-html --cover-package=src
after_success:
  coveralls